### ISSUE TITLE
Finalize project understanding

### ISSUE THREAD

**Issue by MandarGade** [SJSU272Lab/Fall16-Team25#3]
Created a discussion on the understanding document to debate the merits of the current view.

**Comment by varundrogba** [comment]
![sample flow editable](https://cloud.githubusercontent.com/assets/21318180/20148502/e09d0578-a661-11e6-86ce-092340aff7bf.png)
[project flow.txt](https://github.com/SJSU272Lab/Fall16-Team25/files/581382/project.flow.txt)

Considering that school admins have accounts already created. 
1.  School admin will create an event and would be admin of that event. Considering that one school will host event. 
   Admin will create event and set criteria and rules of event.
2.  Host will add participating schools. 
3.  Participating schools will provide parent details(name,email).
4.  Filter algorithm will filter out judges from the parent database list from system database. 
   It also filters out reserve judges. These filtered results will be filled in a mapping.
5.  Admin can send mail invites to parents and parents would accept or reject invite.
6. This information will be adjusted in the mapping accordingly.
7.  Parent attendance at the event will be updated on mapping as and when parent confirm their attendance.
8.  Admin can send announcements through application, either to all judges or selected judges.

Our approach is to avoid maintaining student data as it is not required. We focus on parent data(name, email).

**Comment by rishindrareddy** [comment]
Professor,

Please review our project flow document and flow diagram. We are looking forward for your feedback.

Thank you.

**Comment by varundrogba** [comment]
Considering that school admins have accounts already created. 

1.  School admin will create an event and would be admin of that event. Considering that one school will host event. 
    Admin will create event and set criteria and rules of event.

2.  Host will add participating schools. 

3.  Participating schools will provide parent details(name,email).

4.  Filter algorithm will filter out judges from the parent database list from system database. 
    It also filters out reserve judges. These filtered results will be filled in a mapping.

5.  Admin can send mail invites to parents and parents would accept or reject invite.

6. This information will be adjusted in the mapping accordingly.

7.  Parent attendance at the event will be updated on mapping as and when parent confirm their attendance.

8.  Admin can send announcements through application, either to all judges or selected judges.

Our approach is to avoid maintaining student data as it is not required. We focus on parent data(name, email).
